name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Restrict permissions to minimum required
    permissions:
      contents: read
      deployments: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Test Connection
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          # Test connection with strict host key checking
          if ! ssh -o BatchMode=yes -i ~/.ssh/id_ed25519 $VPS_USERNAME@$VPS_HOST 'exit 0'; then
            echo "Failed to establish SSH connection"
            exit 1
          fi

      - name: Deploy to VPS
        if: success()
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          DEPLOY_PATH: '/home/alex/python/discord-bot-python'
        run: |
          echo "=== Verifying Deployment Path ==="
          if ! ssh $VPS_USERNAME@$VPS_HOST "[ -d '$DEPLOY_PATH' ] && [ -w '$DEPLOY_PATH' ]"; then
            echo "Deployment path does not exist or is not writable"
            exit 1
          fi
          
          echo "=== Starting Deployment ==="
          # Check for rsync with specific error handling
          if ! ssh $VPS_USERNAME@$VPS_HOST 'command -v rsync > /dev/null'; then
            echo "Installing rsync..."
            ssh $VPS_USERNAME@$VPS_HOST 'sudo -n apt-get update && sudo -n apt-get install -y rsync'
          fi
          
          echo "=== Stopping Service ==="
          if ! ssh $VPS_USERNAME@$VPS_HOST 'sudo -n systemctl stop pybot'; then
            echo "Failed to stop service"
            exit 1
          fi
          
          echo "=== Deploying Code ==="
          rsync -az --delete \
            --exclude '.git*' \
            --exclude '__pycache__' \
            --exclude '*.pyc' \
            --exclude '.env' \
            --exclude '.venv' \
            --exclude 'logs/' \
            --exclude 'tmp/' \
            ./ $VPS_USERNAME@$VPS_HOST:$DEPLOY_PATH/
          
          echo "=== Setting up Virtual Environment ==="
          ssh $VPS_USERNAME@$VPS_HOST "cd $DEPLOY_PATH && \
            rm -rf .venv && \
            python3 -m venv .venv && \
            source .venv/bin/activate && \
            python3 -m pip install --upgrade pip && \
            python3 -m pip install -r requirements.txt"
          
          echo "=== Managing Service ==="
          if ! ssh $VPS_USERNAME@$VPS_HOST 'sudo -n systemctl restart pybot'; then
            echo "Failed to restart service"
            exit 1
          fi

      - name: Verify Deployment
        if: success()
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          echo "=== Checking Service Status ==="
          if ! ssh $VPS_USERNAME@$VPS_HOST 'systemctl is-active --quiet pybot'; then
            echo "✗ Service failed to start"
            exit 1
          fi
          echo "✓ Service is running" 